export type Gender = "M" | "F";

export interface DailyReport {
  No: number;
  "Clinic/Physician": string;
  "Ext ID": string;
  "Last Name": string;
  "Passport Number": string;
  "Vaccination Status": string;
  "First Name": string;
  "M.I.": string;
  "Sex(F/M)": Gender;
  "Date of Birth": string;
  "Test Panel": string;
  Date: string;
  Time: string;
  Timezone: string;
  Type: string;
  Storage: string;
  Email: string;
  Address: string;
  City: string;
  State: string;
  Zip: string;
  Country: string;
  Phone: string;
  Nationality: string;
  Method: string;
  "Insurance Co": string;
  "Policy No": string;
  "Group No": string;
  "Sample Vol/Qty": string;
  Comments: string;
  "Entry Verification": string;
  "Order ID": string;
  "Source ID": string;
  "Created At": Date;
  "Shipping Required": boolean;
  "Shipping Address": string;
  "Shipping City": string;
  "Shipping Country": string;
  "Shipping State": string;
  "Shipping Province Code": string;
  "Shipping Zip": string;
  Tax: number;
  Currency: string;
  Amount: string;
  "Line Items": string;
  "Purchased By": string;
  "Practitioner ID": string;
  "Practitioner Name": string;
  Status: string;
  "Appointment Date": string;
  "Appointment Start Time": string;
  "Appointment End Time": string;
}
