# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Practitioner Deployment

on:
  push:
    branches: [practitioner]

jobs:
  deploy_to_practitioner:
    runs-on: ubuntu-latest
    environment: practitioner
    steps:
      - uses: actions/checkout@v2
      - name: Install Firebase Emulator Suite
        run: npm i -g firebase-tools
      - name: install dependencies
        run: npm install
        working-directory: functions
      - name: Jest testing (including firestore rules)
        run: npm run test
        working-directory: functions
      - name: deploy to practitioner
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P practitioner --only functions:acuity,functions:makePayment,functions:createDailyReport
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
